# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Final size of an epidemic
#'
#' @description Calculates the final size of an epidemic outbreak
#' in a population with heterogeneous mixing, and with heterogeneous
#' susceptibility to infection such as that conferred by an immunisation
#' programme.
#'
#' **Note**: This is an internal function that is called by
#' \link[finalsize]{final_size}. This function is somewhat faster, but lacks
#' argument checks found in `final_size`. Use with caution.
#'
#' @param contact_matrix Social contact matrix. Entry \eqn{m_{ij}} gives the
#' average number of contacts in group \eqn{i} reported by participants in
#' group \eqn{j}.
#' @param demography_vector Demography vector. Entry \eqn{v_{i}} gives
#' proportion of total population in group \eqn{i} (model will normalise
#' if needed).
#' @param p_susceptibility A matrix giving the probability that an individual
#' in demography group \eqn{i} is in risk (or susceptibility) group \eqn{j}.
#' Each row represents the overall distribution of individuals in demographic
#' group \eqn{i} across risk groups, and each row *must sum to 1.0*.
#' @param susceptibility A matrix giving the susceptibility of individuals in
#' demographic group \eqn{i} and risk group \eqn{j}.
#' @param solver Which solver to use. Options are "iterative" or "newton", for
#' the iterative solver, or the Newton solver, respectively. The Newton solver
#' only uses the `iterations` and `tolerance` options.
#' @param iterations The number of iterations over which to solve for the final
#' size, unless the error is below the solver tolerance.
#' @param tolerance The solver tolerance, set to `1e-6` by default; solving for
#' final size ends when the error drops below this tolerance.
#' @param step_rate The solver step rate. Defaults to 1.9 as a value found to
#' work well.
#' @param adapt_step Boolean, whether the solver step rate should be changed
#' based on the solver error. Defaults to TRUE.
#'
#' @keywords epidemic model
.final_size <- function(contact_matrix, demography_vector, p_susceptibility, susceptibility, solver = "iterative", iterations = 10000L, tolerance = 1e-6, step_rate = 1.9, adapt_step = TRUE) {
    .Call('_finalsize_final_size_', PACKAGE = 'finalsize', contact_matrix, demography_vector, p_susceptibility, susceptibility, solver, iterations, tolerance, step_rate, adapt_step)
}

