# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_final_size_internal <- function(contact_matrix, demography, p_susceptibility, susceptibility, adapt_step = TRUE, tolerance = 1e-6) {
    .Call('_finalsize_solve_final_size_internal', PACKAGE = 'finalsize', contact_matrix, demography, p_susceptibility, susceptibility, adapt_step, tolerance)
}

