name: cpp-linter

on:
  push:
    paths: "src/**"
    paths-ignore: "src/RcppExports.cpp"
  pull_request:
    branches:
      - "*"
    paths-ignore: "src/RcppExports.cpp"

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'google'
          files-changed-only: false
          thread-comments: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
          exit 1
